// 小学 / 初中 / 高中 词表（内置核心，含中文释义、例句、用法说明）。
// 英文音标/发音音频/同义词/反义词/更多例句由 scripts/build-words.js 在构建期
// 通过 Free Dictionary API 补全；API 不可达时仅用下面这些内置数据兜底，绝不空屏。
// level: PRIMARY=小学, JUNIOR=初中, SENIOR=高中
module.exports = [
  // ===================== 小学 PRIMARY =====================
  { word: "apple", level: "PRIMARY", pos: "n.", cn: "苹果", exampleCn: "我每天吃一个苹果。", usage: "可数名词，复数 apples；是最常见的水果类入门词。" },
  { word: "book", level: "PRIMARY", pos: "n.", cn: "书；书本", exampleCn: "她正在读一本书。", usage: "可数名词，复数 books；动词 book 意为「预订」。" },
  { word: "cat", level: "PRIMARY", pos: "n.", cn: "猫", exampleCn: "那只猫在晒太阳。", usage: "可数名词，复数 cats；常见宠物类单词。" },
  { word: "dog", level: "PRIMARY", pos: "n.", cn: "狗", exampleCn: "狗是人类的好朋友。", usage: "可数名词，复数 dogs；与 cat 相对。" },
  { word: "red", level: "PRIMARY", pos: "adj.", cn: "红色的", exampleCn: "她穿着红色的外套。", usage: "表示颜色的形容词，常作定语修饰名词。" },
  { word: "blue", level: "PRIMARY", pos: "adj.", cn: "蓝色的", exampleCn: "天空是蓝色的。", usage: "颜色词；也常形容「忧郁的」情绪。" },
  { word: "green", level: "PRIMARY", pos: "adj.", cn: "绿色的", exampleCn: "春天树叶变绿了。", usage: "颜色词；也指「环保的」，如 green energy。" },
  { word: "yellow", level: "PRIMARY", pos: "adj.", cn: "黄色的", exampleCn: "香蕉是黄色的。", usage: "颜色词；也可指「胆怯的」。" },
  { word: "water", level: "PRIMARY", pos: "n.", cn: "水", exampleCn: "请给我一杯水。", usage: "不可数名词，不能说 a water；表「水域/海水」时可用复数 waters。" },
  { word: "school", level: "PRIMARY", pos: "n.", cn: "学校", exampleCn: "孩子们去学校上课。", usage: "常搭配 go to school（去上学，不加 the）。" },
  { word: "teacher", level: "PRIMARY", pos: "n.", cn: "老师；教师", exampleCn: "她是一位好老师。", usage: "职业类名词；对应 student（学生）。" },
  { word: "student", level: "PRIMARY", pos: "n.", cn: "学生", exampleCn: "他是三年级的学生。", usage: "对应 teacher；pupil 多指小学生。" },
  { word: "happy", level: "PRIMARY", pos: "adj.", cn: "高兴的；快乐的", exampleCn: "收到礼物她很开心。", usage: "反义词 sad；名词 happiness（幸福）。" },
  { word: "big", level: "PRIMARY", pos: "adj.", cn: "大的", exampleCn: "这是一只大盒子。", usage: "反义词 small；比较级 bigger，最高级 biggest。" },
  { word: "small", level: "PRIMARY", pos: "adj.", cn: "小的", exampleCn: "这只小猫很小。", usage: "反义词 big；强调尺寸小。" },
  { word: "run", level: "PRIMARY", pos: "v.", cn: "跑；奔跑", exampleCn: "男孩在公园里跑。", usage: "不及物；过去式 ran，过去分词 run。" },
  { word: "eat", level: "PRIMARY", pos: "v.", cn: "吃", exampleCn: "我们吃午饭吧。", usage: "过去式 ate，过去分词 eaten。" },
  { word: "play", level: "PRIMARY", pos: "v.", cn: "玩；演奏", exampleCn: "孩子们在外面玩。", usage: "play the piano（弹钢琴）中乐器前加 the。" },
  { word: "read", level: "PRIMARY", pos: "v.", cn: "读；阅读", exampleCn: "他每天读书。", usage: "过去式 read 读作 /red/，过去分词 read。" },
  { word: "write", level: "PRIMARY", pos: "v.", cn: "写", exampleCn: "请写下你的名字。", usage: "名词 writer 意为「作家」；过去式 wrote。" },
  { word: "good", level: "PRIMARY", pos: "adj.", cn: "好的；优良的", exampleCn: "这是一本好书。", usage: "反义词 bad；比较级 better，最高级 best。" },
  { word: "hello", level: "PRIMARY", pos: "int.", cn: "你好", exampleCn: "他向我打招呼说 hello。", usage: "见面时的问候语；回应可用 hi / hello。" },
  { word: "thank", level: "PRIMARY", pos: "v.", cn: "感谢；谢谢", exampleCn: "谢谢你的帮助。", usage: "thank you = 谢谢你；形容词 thankful（感激的）。" },
  { word: "friend", level: "PRIMARY", pos: "n.", cn: "朋友", exampleCn: "她是我的好朋友。", usage: "可数，复数 friends；形容词 friendly（友好的）。" },
  { word: "family", level: "PRIMARY", pos: "n.", cn: "家庭；家人", exampleCn: "我爱我的家人。", usage: "作「家庭整体」时视为单数，如 My family is big." },
  { word: "tree", level: "PRIMARY", pos: "n.", cn: "树", exampleCn: "院子里有一棵大树。", usage: "可数名词，复数 trees。" },
  { word: "sun", level: "PRIMARY", pos: "n.", cn: "太阳", exampleCn: "太阳从东方升起。", usage: "世界上独一无二，通常加 the：the sun。" },
  { word: "moon", level: "PRIMARY", pos: "n.", cn: "月亮", exampleCn: "今晚的月亮很圆。", usage: "通常加 the：the moon。" },
  { word: "star", level: "PRIMARY", pos: "n.", cn: "星星；恒星", exampleCn: "夜空中有许多星星。", usage: "可数，复数 stars；也指「明星」。" },
  { word: "fish", level: "PRIMARY", pos: "n.", cn: "鱼", exampleCn: "猫喜欢吃鱼。", usage: "单复同形（fish）；指不同种类时用 fishes。" },
  { word: "bird", level: "PRIMARY", pos: "n.", cn: "鸟", exampleCn: "一只小鸟在歌唱。", usage: "可数名词，复数 birds。" },
  { word: "love", level: "PRIMARY", pos: "v./n.", cn: "爱；喜爱", exampleCn: "她爱她的家人。", usage: "可作动词也可作名词；lovely 意为「可爱的」。" },
  { word: "help", level: "PRIMARY", pos: "v.", cn: "帮助", exampleCn: "你能帮我一下吗？", usage: "helpful（有用的）；can't help doing 忍不住做。" },
  { word: "open", level: "PRIMARY", pos: "v.", cn: "打开", exampleCn: "请打开门。", usage: "反义词 close；形容词 open（开着的）。" },
  { word: "close", level: "PRIMARY", pos: "v.", cn: "关闭", exampleCn: "请关上窗户。", usage: "反义词 open；形容词 closed（关着的）。" },
  { word: "go", level: "PRIMARY", pos: "v.", cn: "去；走", exampleCn: "我们去看电影吧。", usage: "过去式 went，过去分词 gone；go to school 去上学。" },
  { word: "come", level: "PRIMARY", pos: "v.", cn: "来", exampleCn: "他明天会来。", usage: "反义词 go；过去式 came。" },
  { word: "see", level: "PRIMARY", pos: "v.", cn: "看见；明白", exampleCn: "我能看见那座山。", usage: "过去式 saw，过去分词 seen。" },
  { word: "look", level: "PRIMARY", pos: "v.", cn: "看；看起来", exampleCn: "看那朵云！", usage: "look at（看……）；look 强调「看」的动作。" },
  { word: "hear", level: "PRIMARY", pos: "v.", cn: "听见", exampleCn: "我听见了歌声。", usage: "过去式 heard；名词 hearing（听力）。" },
  { word: "sing", level: "PRIMARY", pos: "v.", cn: "唱；唱歌", exampleCn: "她唱了一首歌。", usage: "过去式 sang；名词 singer 意为「歌手」。" },

  // ===================== 初中 JUNIOR =====================
  { word: "able", level: "JUNIOR", pos: "adj.", cn: "能够的；有能力的", exampleCn: "他能够完成这项任务。", usage: "be able to do 表示「能够」，相当于 can 的多种时态形式。" },
  { word: "accept", level: "JUNIOR", pos: "v.", cn: "接受；同意", exampleCn: "她接受了我的道歉。", usage: "反义词 refuse（拒绝）；名词 acceptance。" },
  { word: "achieve", level: "JUNIOR", pos: "v.", cn: "实现；达到", exampleCn: "努力终会实现梦想。", usage: "achieve a goal 实现目标；名词 achievement（成就）。" },
  { word: "activity", level: "JUNIOR", pos: "n.", cn: "活动", exampleCn: "课外活动很丰富。", usage: "可数名词，复数 activities；形容词 active（活跃的）。" },
  { word: "advice", level: "JUNIOR", pos: "n.", cn: "建议；忠告", exampleCn: "他给了我好建议。", usage: "不可数名词，不能说 an advice；a piece of advice 一条建议。" },
  { word: "afraid", level: "JUNIOR", pos: "adj.", cn: "害怕的；担心的", exampleCn: "孩子怕黑。", usage: "be afraid of sth. 害怕某事；be afraid to do 不敢做。" },
  { word: "again", level: "JUNIOR", pos: "adv.", cn: "再一次；又", exampleCn: "请再试一次。", usage: "表重复，常置于句末或动词之后。" },
  { word: "already", level: "JUNIOR", pos: "adv.", cn: "已经", exampleCn: "我已经做完了。", usage: "多用于肯定句完成时；否定/疑问常用 yet。" },
  { word: "amazing", level: "JUNIOR", pos: "adj.", cn: "令人惊奇的", exampleCn: "这是一场惊人的表演。", usage: "由动词 amaze 变来；修饰物；修饰人用 amazed。" },
  { word: "ancient", level: "JUNIOR", pos: "adj.", cn: "古老的；古代的", exampleCn: "这是一座古城。", usage: "反义词 modern（现代的）。" },
  { word: "another", level: "JUNIOR", pos: "adj./pron.", cn: "另一个；再一个", exampleCn: "再给我一个杯子。", usage: "an + other，后接单数名词；泛指「另一个」。" },
  { word: "appear", level: "JUNIOR", pos: "v.", cn: "出现；显得", exampleCn: "太阳出现在地平线上。", usage: "反义词 disappear（消失）；作系动词表「似乎」。" },
  { word: "argue", level: "JUNIOR", pos: "v.", cn: "争论；争吵", exampleCn: "他们为小事争吵。", usage: "argue with sb. 与某人争论；名词 argument。" },
  { word: "around", level: "JUNIOR", pos: "prep./adv.", cn: "在……周围；大约", exampleCn: "公园周围有很多树。", usage: "表地点「围绕」或表时间/数量「大约」。" },
  { word: "artist", level: "JUNIOR", pos: "n.", cn: "艺术家；画家", exampleCn: "她想成为艺术家。", usage: "由 art（艺术）派生；artistic 艺术的。" },
  { word: "attract", level: "JUNIOR", pos: "v.", cn: "吸引；引起", exampleCn: "鲜艳的颜色吸引蜜蜂。", usage: "attract one's attention 吸引注意；名词 attraction。" },
  { word: "avoid", level: "JUNIOR", pos: "v.", cn: "避免；回避", exampleCn: "请避免迟到。", usage: "avoid doing sth. 避免做某事（后接动名词）。" },
  { word: "basic", level: "JUNIOR", pos: "adj.", cn: "基本的；基础的", exampleCn: "这是基本语法。", usage: "名词 base（基础）或 basis；反义词 advanced。" },
  { word: "behavior", level: "JUNIOR", pos: "n.", cn: "行为；举止", exampleCn: "他的行为很得体。", usage: "不可数名词；形容词 behavioral（行为的）。" },
  { word: "belong", level: "JUNIOR", pos: "v.", cn: "属于；应归入", exampleCn: "这本书属于图书馆。", usage: "belong to sb. 属于某人，无进行时态。" },
  { word: "build", level: "JUNIOR", pos: "v.", cn: "建造；建立", exampleCn: "他们建了一座桥。", usage: "过去式/分词 built；名词 building（建筑物）。" },
  { word: "cancel", level: "JUNIOR", pos: "v.", cn: "取消；撤销", exampleCn: "航班因天气取消了。", usage: "过去式 cancelled（英）/canceled（美）；名词 cancellation。" },
  { word: "century", level: "JUNIOR", pos: "n.", cn: "世纪", exampleCn: "二十一世纪开始了。", usage: "100 年为一世纪；复数 centuries。" },
  { word: "certain", level: "JUNIOR", pos: "adj.", cn: "确定的；某个", exampleCn: "我确信他会来。", usage: "be certain of/about 确信；a certain 某一（不具体）。" },
  { word: "challenge", level: "JUNIOR", pos: "n./v.", cn: "挑战", exampleCn: "这是个不小的挑战。", usage: "形容词 challenging（有挑战性的）。" },
  { word: "character", level: "JUNIOR", pos: "n.", cn: "性格；角色；汉字", exampleCn: "他性格开朗。", usage: "多义词：人品 / 故事人物 / 文字符号。" },
  { word: "climate", level: "JUNIOR", pos: "n.", cn: "气候", exampleCn: "全球气候在变化。", usage: "区别 weather（天气，短时）；climate 指长期气候。" },
  { word: "collect", level: "JUNIOR", pos: "v.", cn: "收集；采集", exampleCn: "他收集邮票。", usage: "collect stamps 集邮；名词 collection。" },
  { word: "communicate", level: "JUNIOR", pos: "v.", cn: "交流；沟通", exampleCn: "我们用邮件沟通。", usage: "communicate with sb.；名词 communication。" },
  { word: "compare", level: "JUNIOR", pos: "v.", cn: "比较；对比", exampleCn: "比较两种方案。", usage: "compare A with B 比较；compare A to B 把 A 比作 B。" },
  { word: "complete", level: "JUNIOR", pos: "v./adj.", cn: "完成；完整的", exampleCn: "任务已完成。", usage: "作动词「完成」；作形容词「彻底的」，反义词 incomplete。" },
  { word: "consider", level: "JUNIOR", pos: "v.", cn: "考虑；认为", exampleCn: "请考虑我的建议。", usage: "consider doing 考虑做；consider sb. (as) 认为。" },
  { word: "continue", level: "JUNIOR", pos: "v.", cn: "继续", exampleCn: "雨继续下着。", usage: "continue doing/to do 继续做；名词 continuation。" },
  { word: "control", level: "JUNIOR", pos: "v./n.", cn: "控制；支配", exampleCn: "控制自己的情绪。", usage: "under control 受控；out of control 失控。" },
  { word: "correct", level: "JUNIOR", pos: "adj./v.", cn: "正确的；改正", exampleCn: "请改正错误。", usage: "作形容词「对的」，反义词 wrong；作动词「纠正」。" },
  { word: "create", level: "JUNIOR", pos: "v.", cn: "创造；创作", exampleCn: "他创造了新纪录。", usage: "名词 creation；creative 有创造力的。" },
  { word: "culture", level: "JUNIOR", pos: "n.", cn: "文化", exampleCn: "中西方文化差异很大。", usage: "形容词 cultural（文化的）。" },
  { word: "decide", level: "JUNIOR", pos: "v.", cn: "决定", exampleCn: "我们决定去旅行。", usage: "decide to do 决定做；名词 decision。" },
  { word: "develop", level: "JUNIOR", pos: "v.", cn: "发展；开发；养成", exampleCn: "城市在快速发展。", usage: "develop a habit 养成习惯；名词 development。" },
  { word: "discover", level: "JUNIOR", pos: "v.", cn: "发现", exampleCn: "哥伦布发现新大陆。", usage: "指发现原有事物；名词 discovery，反义词 invent（发明）。" },
  { word: "discuss", level: "JUNIOR", pos: "v.", cn: "讨论", exampleCn: "我们讨论了计划。", usage: "discuss sth. with sb.；名词 discussion。" },
  { word: "environment", level: "JUNIOR", pos: "n.", cn: "环境", exampleCn: "保护环境很重要。", usage: "形容词 environmental（环境的）；protect the environment 环保。" },
  { word: "explain", level: "JUNIOR", pos: "v.", cn: "解释；说明", exampleCn: "请解释原因。", usage: "explain sth. to sb.；名词 explanation。" },
  { word: "famous", level: "JUNIOR", pos: "adj.", cn: "著名的", exampleCn: "他是一位著名作家。", usage: "be famous for 因……著名；be famous as 作为……著名。" },
  { word: "follow", level: "JUNIOR", pos: "v.", cn: "跟随；遵循", exampleCn: "请遵循规则。", usage: "follow the rules 遵守规则；反义词 lead（领导）。" },
  { word: "foreign", level: "JUNIOR", pos: "adj.", cn: "外国的；对外的", exampleCn: "他在外国学习。", usage: "foreign language 外语；foreigner 外国人。" },
  { word: "forget", level: "JUNIOR", pos: "v.", cn: "忘记", exampleCn: "我忘了他的名字。", usage: "反义词 remember；过去式 forgot，过去分词 forgotten。" },
  { word: "gather", level: "JUNIOR", pos: "v.", cn: "聚集；收集", exampleCn: "大家聚在广场上。", usage: "gather information 收集信息；反义词 scatter（散开）。" },
  { word: "guess", level: "JUNIOR", pos: "v.", cn: "猜测；推测", exampleCn: "我猜他不会来。", usage: "make a guess 猜一下；I guess 我想/大概。" },
  { word: "habit", level: "JUNIOR", pos: "n.", cn: "习惯", exampleCn: "阅读是个好习惯。", usage: "form a habit 养成习惯；good/bad habit 好/坏习惯。" },
  { word: "happen", level: "JUNIOR", pos: "v.", cn: "发生", exampleCn: "事故是怎么发生的？", usage: "不及物，无被动；sth. happened to sb. 某人出了某事。" },
  { word: "healthy", level: "JUNIOR", pos: "adj.", cn: "健康的", exampleCn: "多吃蔬果更健康。", usage: "名词 health（健康）；keep healthy 保持健康。" },
  { word: "improve", level: "JUNIOR", pos: "v.", cn: "改善；提高", exampleCn: "他的英语进步了。", usage: "improvement 进步；反义词 worsen（恶化）。" },
  { word: "include", level: "JUNIOR", pos: "v.", cn: "包括；包含", exampleCn: "价格含税费。", usage: "including 包括；反义词 exclude（排除）。" },
  { word: "increase", level: "JUNIOR", pos: "v./n.", cn: "增加；增长", exampleCn: "销量在增加。", usage: "反义词 decrease（减少）；on the increase 在增长。" },
  { word: "introduce", level: "JUNIOR", pos: "v.", cn: "介绍；引入", exampleCn: "请介绍一下你自己。", usage: "introduce A to B 把 A 介绍给 B；名词 introduction。" },
  { word: "invite", level: "JUNIOR", pos: "v.", cn: "邀请", exampleCn: "他邀请我吃饭。", usage: "invite sb. to 邀请某人去；名词 invitation。" },
  { word: "knowledge", level: "JUNIOR", pos: "n.", cn: "知识；学问", exampleCn: "知识就是力量。", usage: "不可数名词；形容词 knowledgeable（博学的）。" },
  { word: "language", level: "JUNIOR", pos: "n.", cn: "语言", exampleCn: "英语是世界语言。", usage: "可数名词；mother tongue 母语。" },
  { word: "learn", level: "JUNIOR", pos: "v.", cn: "学习；学会", exampleCn: "我们学英语。", usage: "反义词 teach（教）；learn from 向……学习。" },
  { word: "mention", level: "JUNIOR", pos: "v.", cn: "提到；提及", exampleCn: "他提到了那件事。", usage: "Don't mention it. 别客气（回应感谢）。" },
  { word: "modern", level: "JUNIOR", pos: "adj.", cn: "现代的；时髦的", exampleCn: "这是一座现代建筑。", usage: "反义词 ancient（古老的）。" },
  { word: "natural", level: "JUNIOR", pos: "adj.", cn: "自然的；天生的", exampleCn: "这是一种自然现象。", usage: "名词 nature（自然）；反义词 artificial（人造的）。" },
  { word: "news", level: "JUNIOR", pos: "n.", cn: "新闻；消息", exampleCn: "今天有个好消息。", usage: "不可数名词，谓语用单数；a piece of news 一条新闻。" },
  { word: "offer", level: "JUNIOR", pos: "v.", cn: "提供；提议", exampleCn: "他提供了帮助。", usage: "offer to do 主动提出做；offer sb. sth. 向某人提供。" },
  { word: "opinion", level: "JUNIOR", pos: "n.", cn: "观点；意见", exampleCn: "每个人都有看法。", usage: "in my opinion 我认为；have an opinion on 对……有看法。" },
  { word: "paint", level: "JUNIOR", pos: "v.", cn: "绘画；涂漆", exampleCn: "他在画一幅画。", usage: "名词 painter（画家）；painting（画作）。" },
  { word: "patient", level: "JUNIOR", pos: "adj.", cn: "耐心的", exampleCn: "老师很有耐心。", usage: "反义词 impatient；名词 patience（耐心）。" },
  { word: "perform", level: "JUNIOR", pos: "v.", cn: "表演；执行", exampleCn: "他们表演了节目。", usage: "performance 表演/表现；perform well 表现出色。" },
  { word: "plan", level: "JUNIOR", pos: "n./v.", cn: "计划；打算", exampleCn: "我们有个计划。", usage: "plan to do 计划做；make a plan 制定计划。" },
  { word: "plant", level: "JUNIOR", pos: "n./v.", cn: "植物；种植", exampleCn: "春天种树。", usage: "反义词 animal（动物）；plant trees 植树。" },
  { word: "popular", level: "JUNIOR", pos: "adj.", cn: "受欢迎的；流行的", exampleCn: "这首歌很流行。", usage: "be popular with 受……欢迎；反义词 unpopular。" },
  { word: "practice", level: "JUNIOR", pos: "v./n.", cn: "练习；实践", exampleCn: "熟能生巧。", usage: "practice doing 练习做；美 practise 作动词，practice 作名词。" },
  { word: "prepare", level: "JUNIOR", pos: "v.", cn: "准备", exampleCn: "准备考试。", usage: "prepare for 为……准备；preparation 准备。" },
  { word: "prevent", level: "JUNIOR", pos: "v.", cn: "防止；阻止", exampleCn: "预防疾病。", usage: "prevent...from doing 阻止……做；名词 prevention。" },
  { word: "proud", level: "JUNIOR", pos: "adj.", cn: "骄傲的；自豪的", exampleCn: "他为儿子感到自豪。", usage: "be proud of 以……为傲；名词 pride。" },
  { word: "quiet", level: "JUNIOR", pos: "adj.", cn: "安静的；宁静的", exampleCn: "请保持安静。", usage: "反义词 noisy（吵闹的）；keep quiet 保持安静。" },
  { word: "realize", level: "JUNIOR", pos: "v.", cn: "意识到；实现", exampleCn: "他意识到自己错了。", usage: "realize a dream 实现梦想；名词 realization。" },
  { word: "receive", level: "JUNIOR", pos: "v.", cn: "收到；接待", exampleCn: "我收到一封信。", usage: "反义词 send（寄）；名词 receipt（收据）。" },
  { word: "remain", level: "JUNIOR", pos: "v.", cn: "保持；留下", exampleCn: "问题依然存在。", usage: "作系动词「保持」，后接形容词；remain silent 保持沉默。" },
  { word: "remember", level: "JUNIOR", pos: "v.", cn: "记得；记住", exampleCn: "我记得那件事。", usage: "反义词 forget；remember to do 记得去做。" },
  { word: "require", level: "JUNIOR", pos: "v.", cn: "需要；要求", exampleCn: "入学需要考试。", usage: "require doing/to do；require sth. of sb. 对某人要求。" },
  { word: "research", level: "JUNIOR", pos: "n.", cn: "研究；调查", exampleCn: "他在做科学研究。", usage: "不可数；do research on 对……做研究。" },
  { word: "return", level: "JUNIOR", pos: "v.", cn: "返回；归还", exampleCn: "他明天回来。", usage: "return to 回到；return sth. to 把……还给。" },
  { word: "safe", level: "JUNIOR", pos: "adj.", cn: "安全的", exampleCn: "这里很安全。", usage: "反义词 dangerous；名词 safety（安全）。" },
  { word: "search", level: "JUNIOR", pos: "v.", cn: "搜索；寻找", exampleCn: "我在搜索资料。", usage: "search for 寻找；search engine 搜索引擎。" },
  { word: "serve", level: "JUNIOR", pos: "v.", cn: "服务；招待", exampleCn: "这家店服务很好。", usage: "service 服务（名词）；serve as 充当。" },
  { word: "several", level: "JUNIOR", pos: "adj.", cn: "几个；若干", exampleCn: "我们有几个问题。", usage: "后接复数可数名词，比 some 更明确数量。" },
  { word: "share", level: "JUNIOR", pos: "v.", cn: "分享；分担", exampleCn: "分享快乐。", usage: "share sth. with sb. 与某人分享；share the cost 分摊费用。" },
  { word: "similar", level: "JUNIOR", pos: "adj.", cn: "相似的；类似的", exampleCn: "两者很相似。", usage: "be similar to 与……相似；反义词 different。" },
  { word: "society", level: "JUNIOR", pos: "n.", cn: "社会", exampleCn: "服务社会。", usage: "形容词 social（社会的）；modern society 现代社会。" },
  { word: "solve", level: "JUNIOR", pos: "v.", cn: "解决；解答", exampleCn: "我们一起解决问题。", usage: "solve a problem 解决问题；名词 solution。" },
  { word: "spend", level: "JUNIOR", pos: "v.", cn: "花费；度过", exampleCn: "他花了两小时做作业。", usage: "sb. spend(s) time/money on sth./(in) doing 人花费。" },
  { word: "strange", level: "JUNIOR", pos: "adj.", cn: "奇怪的；陌生的", exampleCn: "真奇怪！", usage: "反义词 familiar（熟悉的）；名词 stranger（陌生人）。" },
  { word: "succeed", level: "JUNIOR", pos: "v.", cn: "成功", exampleCn: "他终于成功了。", usage: "succeed in doing 成功做成；名词 success，反义词 fail。" },
  { word: "suggest", level: "JUNIOR", pos: "v.", cn: "建议；提议", exampleCn: "我建议早点出发。", usage: "suggest doing（不接 to do）；名词 suggestion。" },
  { word: "support", level: "JUNIOR", pos: "v.", cn: "支持；支撑", exampleCn: "家人支持我的决定。", usage: "反义词 oppose（反对）；名词 support。" },
  { word: "surface", level: "JUNIOR", pos: "n.", cn: "表面；水面", exampleCn: "水面很平静。", usage: "反义词 bottom（底部）；on the surface 表面上。" },
  { word: "surprise", level: "JUNIOR", pos: "n./v.", cn: "惊讶；使吃惊", exampleCn: "这真让人意外。", usage: "to one's surprise 令某人惊讶的是；surprised/surprising。" },
  { word: "technology", level: "JUNIOR", pos: "n.", cn: "科技；技术", exampleCn: "科技发展很快。", usage: "形容词 technical（技术的）；high technology 高科技。" },
  { word: "temperature", level: "JUNIOR", pos: "n.", cn: "温度；体温", exampleCn: "今天气温很高。", usage: "take one's temperature 量体温；high/low temperature 高/低温。" },
  { word: "train", level: "JUNIOR", pos: "n./v.", cn: "火车；训练", exampleCn: "他乘火车去北京。", usage: "作动词「训练」；trainer 教练；training 训练。" },
  { word: "translate", level: "JUNIOR", pos: "v.", cn: "翻译", exampleCn: "请把这句译成中文。", usage: "translate A into B 把 A 译成 B；translation 翻译。" },
  { word: "travel", level: "JUNIOR", pos: "v.", cn: "旅行；游历", exampleCn: "他喜欢到处旅行。", usage: "名词 traveler（旅行者）；travel abroad 出国旅行。" },
  { word: "trust", level: "JUNIOR", pos: "v.", cn: "信任；信赖", exampleCn: "我信任你。", usage: "trust sb. 信任某人；反义词 distrust。" },
  { word: "unable", level: "JUNIOR", pos: "adj.", cn: "不能的；无法的", exampleCn: "他无法前来。", usage: "be unable to do 不能做；反义词 able。" },
  { word: "university", level: "JUNIOR", pos: "n.", cn: "大学", exampleCn: "他考上了大学。", usage: "可数，注意 a university（u 发辅音 /j/）。" },
  { word: "usual", level: "JUNIOR", pos: "adj.", cn: "通常的；惯常的", exampleCn: "一切如常。", usage: "as usual 像往常一样；反义词 unusual。" },
  { word: "value", level: "JUNIOR", pos: "n.", cn: "价值；重要性", exampleCn: "这很有价值。", usage: "形容词 valuable（有价值的）；反义词 valueless。" },
  { word: "various", level: "JUNIOR", pos: "adj.", cn: "各种各样的；不同的", exampleCn: "有各种选择。", usage: "由 vary（变化）派生；后接复数名词。" },
  { word: "weight", level: "JUNIOR", pos: "n.", cn: "重量；体重", exampleCn: "这只猫多重？", usage: "形容词 heavy（重的）；lose/gain weight 减/增重。" },
  { word: "wide", level: "JUNIOR", pos: "adj.", cn: "宽的；广泛的", exampleCn: "马路很宽。", usage: "反义词 narrow；副词 widely（广泛地）。" },
  { word: "win", level: "JUNIOR", pos: "v.", cn: "赢；获胜", exampleCn: "我们赢了比赛。", usage: "反义词 lose；过去式 won；win a prize 获奖。" },

  // ===================== 高中 SENIOR =====================
  { word: "abandon", level: "SENIOR", pos: "v.", cn: "抛弃；放弃；离弃", exampleCn: "暴风雨中他们被迫弃船。", usage: "反义词 keep；abandon oneself to 沉溺于。" },
  { word: "absorb", level: "SENIOR", pos: "v.", cn: "吸收；使专注", exampleCn: "海绵吸水很快。", usage: "be absorbed in 专心致志于；absorbed 专注的。" },
  { word: "accelerate", level: "SENIOR", pos: "v.", cn: "加速；促进", exampleCn: "经济正在加速复苏。", usage: "反义词 decelerate/slow down；名词 acceleration。" },
  { word: "access", level: "SENIOR", pos: "n./v.", cn: "进入；使用权；获取", exampleCn: "学生可自由访问图书馆。", usage: "have access to 有机会/权利使用；accessible 易接近的。" },
  { word: "accompany", level: "SENIOR", pos: "v.", cn: "陪伴；伴随", exampleCn: "母亲陪女儿去上学。", usage: "accompany sb. to 陪某人去；company 公司/陪伴。" },
  { word: "accomplish", level: "SENIOR", pos: "v.", cn: "完成；实现", exampleCn: "我们终于完成目标。", usage: "强调「圆满完成」，近义词 achieve；accomplishment 成就。" },
  { word: "accurate", level: "SENIOR", pos: "adj.", cn: "准确的；精确的", exampleCn: "这块表走得很准。", usage: "反义词 inaccurate；accuracy 准确性。" },
  { word: "accuse", level: "SENIOR", pos: "v.", cn: "控告；指责", exampleCn: "他被控偷窃。", usage: "accuse sb. of (doing) 指控某人（做）……。" },
  { word: "acquire", level: "SENIOR", pos: "v.", cn: "获得；习得", exampleCn: "他用一年学会了法语。", usage: "acquire knowledge/skill 习得知识/技能；反义词 lose。" },
  { word: "adapt", level: "SENIOR", pos: "v.", cn: "适应；改编", exampleCn: "他很快适应了新环境。", usage: "adapt to 适应；adapt...for 将……改编为。" },
  { word: "adequate", level: "SENIOR", pos: "adj.", cn: "足够的；适当的", exampleCn: "证据尚不充分。", usage: "反义词 inadequate；指「刚好够」，不如 enough 口语化。" },
  { word: "adjust", level: "SENIOR", pos: "v.", cn: "调整；适应", exampleCn: "他需要时间适应新环境。", usage: "adjust to 适应；adjust oneself 调整自己。" },
  { word: "admire", level: "SENIOR", pos: "v.", cn: "钦佩；欣赏", exampleCn: "我十分钦佩她的勇气。", usage: "admire sb. for 因……钦佩；名词 admiration。" },
  { word: "adopt", level: "SENIOR", pos: "v.", cn: "采用；收养", exampleCn: "公司采用了新技术。", usage: "adopt a policy 采纳政策；adoption 采用/收养。" },
  { word: "advance", level: "SENIOR", pos: "v./n.", cn: "前进；进步；预付", exampleCn: "科学在不断进步。", usage: "in advance 提前；反义词 retreat（撤退）。" },
  { word: "advocate", level: "SENIOR", pos: "v.", cn: "提倡；拥护", exampleCn: "他倡导绿色出行。", usage: "advocate doing 提倡做；名词 advocate 拥护者。" },
  { word: "affect", level: "SENIOR", pos: "v.", cn: "影响；打动", exampleCn: "天气会影响人的心情。", usage: "作动词「影响」；区别 effect（名词/动词「实现」）。" },
  { word: "aggressive", level: "SENIOR", pos: "adj.", cn: "好斗的；进取的", exampleCn: "公司采取激进扩张策略。", usage: "可贬义「侵略性的」或褒义「有冲劲的」。" },
  { word: "allocate", level: "SENIOR", pos: "v.", cn: "分配；拨出", exampleCn: "预算被分配完毕。", usage: "allocate funds/resources 分配资金/资源；allocation 分配。" },
  { word: "alternative", level: "SENIOR", pos: "adj./n.", cn: "替代的；选择", exampleCn: "我们有备选方案。", usage: "have no alternative but to 别无选择只能；alternative energy 新能源。" },
  { word: "ambiguous", level: "SENIOR", pos: "adj.", cn: "含糊的；模棱两可的", exampleCn: "这句话含义模糊。", usage: "反义词 clear/unambiguous；ambiguity 歧义。" },
  { word: "ambitious", level: "SENIOR", pos: "adj.", cn: "有雄心的；野心勃勃的", exampleCn: "他立下了远大的目标。", usage: "ambition 雄心；an ambitious plan 宏伟计划。" },
  { word: "analyze", level: "SENIOR", pos: "v.", cn: "分析；解析", exampleCn: "请分析这些数据。", usage: "名词 analysis（分析）；analytical 分析的。" },
  { word: "annual", level: "SENIOR", pos: "adj.", cn: "每年的；年度的", exampleCn: "公司召开年度会议。", usage: "annually 每年；an annual report 年度报告。" },
  { word: "anticipate", level: "SENIOR", pos: "v.", cn: "预期；期望", exampleCn: "我们预料到会有阻力。", usage: "近义词 expect；anticipate doing 预期做。" },
  { word: "appreciate", level: "SENIOR", pos: "v.", cn: "欣赏；感激；增值", exampleCn: "我很感激你的帮助。", usage: "I'd appreciate it if 若……不胜感激；appreciation 欣赏。" },
  { word: "approve", level: "SENIOR", pos: "v.", cn: "批准；赞成", exampleCn: "委员会批准了计划。", usage: "approve of 赞成；反义词 disapprove；approval 批准。" },
  { word: "assist", level: "SENIOR", pos: "v.", cn: "帮助；协助", exampleCn: "志愿者协助维持秩序。", usage: "assist sb. with/in 协助；assistance 帮助；assistant 助手。" },
  { word: "assume", level: "SENIOR", pos: "v.", cn: "假定；承担", exampleCn: "我们假定他会准时到。", usage: "assume responsibility 承担责任；assumption 假设。" },
  { word: "attain", level: "SENIOR", pos: "v.", cn: "达到；获得", exampleCn: "他达到了预期目标。", usage: "attain one's goal 达成目标；近义词 achieve。" },
  { word: "attribute", level: "SENIOR", pos: "v.", cn: "把……归因于；特性", exampleCn: "他把成功归于勤奋。", usage: "attribute A to B 把 A 归因于 B；名词 attribute 特质。" },
  { word: "aware", level: "SENIOR", pos: "adj.", cn: "意识到的；知道的", exampleCn: "人们越来越关注环保。", usage: "be aware of 意识到；awareness 意识；反义词 unaware。" },
  { word: "beneficial", level: "SENIOR", pos: "adj.", cn: "有益的；有利的", exampleCn: "运动对健康有益。", usage: "be beneficial to 对……有益；名词 benefit（益处）。" },
  { word: "circumstance", level: "SENIOR", pos: "n.", cn: "环境；情况", exampleCn: "在这种情况之下只能让步。", usage: "under the circumstances 在此情况下；复数表「境况」。" },
  { word: "comment", level: "SENIOR", pos: "n./v.", cn: "评论；意见", exampleCn: "请对这件事发表看法。", usage: "comment on 对……评论；No comment. 无可奉告。" },
  { word: "commit", level: "SENIOR", pos: "v.", cn: "承诺；犯（错）", exampleCn: "他承诺会来。", usage: "commit to 致力于；commit a crime 犯罪；committed 坚定的。" },
  { word: "compensate", level: "SENIOR", pos: "v.", cn: "补偿；赔偿", exampleCn: "公司补偿了损失。", usage: "compensate for 补偿；compensation 补偿金。" },
  { word: "complex", level: "SENIOR", pos: "adj.", cn: "复杂的；复合的", exampleCn: "这是个复杂的问题。", usage: "反义词 simple；complexity 复杂性。" },
  { word: "comprehend", level: "SENIOR", pos: "v.", cn: "理解；领会", exampleCn: "我无法完全理解这篇文章。", usage: "comprehension 理解力；comprehensive 全面的。" },
  { word: "concentrate", level: "SENIOR", pos: "v.", cn: "集中；全神贯注", exampleCn: "请集中注意力。", usage: "concentrate on 专心于；concentration 专注。" },
  { word: "conclude", level: "SENIOR", pos: "v.", cn: "总结；断定；结束", exampleCn: "会议到此结束。", usage: "conclude that 断定；conclusion 结论。" },
  { word: "conduct", level: "SENIOR", pos: "v.", cn: "引导；进行；表现", exampleCn: "他主持了这项实验。", usage: "conduct a survey 进行调查；conductor 导体/指挥。" },
  { word: "confirm", level: "SENIOR", pos: "v.", cn: "证实；确认", exampleCn: "请确认收到邮件。", usage: "confirm a booking 确认预订；confirmation 确认函。" },
  { word: "consequence", level: "SENIOR", pos: "n.", cn: "后果；结果", exampleCn: "后果很严重。", usage: "as a consequence 因此；consequent 随之发生的。" },
  { word: "considerate", level: "SENIOR", pos: "adj.", cn: "体贴的；周到的", exampleCn: "她对人很体贴。", usage: "considerate of sb. 体谅某人；consider 考虑（动词）。" },
  { word: "consume", level: "SENIOR", pos: "v.", cn: "消耗；消费", exampleCn: "这台旧空调很费电。", usage: "consumer 消费者；consumption 消耗量。" },
  { word: "contribute", level: "SENIOR", pos: "v.", cn: "贡献；促成", exampleCn: "每人都贡献力量。", usage: "contribute to 促成/贡献于；contribution 贡献。" },
  { word: "convince", level: "SENIOR", pos: "v.", cn: "说服；使信服", exampleCn: "我终于说服了他。", usage: "convince sb. of/that 使某人相信；convincing 令人信服的。" },
  { word: "crucial", level: "SENIOR", pos: "adj.", cn: "关键的；至关重要的", exampleCn: "这是关键的一步。", usage: "be crucial to/for 对……至关重要；近义词 vital。" },
  { word: "declare", level: "SENIOR", pos: "v.", cn: "宣布；声明", exampleCn: "他宣布了最终结果。", usage: "declare war 宣战；declaration 宣言/申报。" },
  { word: "decline", level: "SENIOR", pos: "v.", cn: "下降；衰退；拒绝", exampleCn: "销量开始下滑。", usage: "作「拒绝」较正式；反义词 increase/rise。" },
  { word: "deliberate", level: "SENIOR", pos: "adj.", cn: "故意的；深思熟虑的", exampleCn: "那是故意的破坏。", usage: "反义词 accidental（偶然的）；deliberately 故意地。" },
  { word: "demonstrate", level: "SENIOR", pos: "v.", cn: "证明；演示；示威", exampleCn: "他演示了仪器的用法。", usage: "demonstrate how 演示如何；demonstration 演示/示威。" },
  { word: "distinguish", level: "SENIOR", pos: "v.", cn: "区分；辨别", exampleCn: "很难区分这对双胞胎。", usage: "distinguish A from B 区分；distinguished 卓越的。" },
  { word: "distribute", level: "SENIOR", pos: "v.", cn: "分配；分发", exampleCn: "志愿者分发物资。", usage: "distribute sth. to 分发；distribution 分配/分销。" },
  { word: "dominate", level: "SENIOR", pos: "v.", cn: "主导；支配；占优势", exampleCn: "主队占据了上风。", usage: "dominant 主导的；domination 支配。" },
  { word: "eliminate", level: "SENIOR", pos: "v.", cn: "消除；淘汰；排除", exampleCn: "我们必须消除隐患。", usage: "eliminate poverty 消除贫困；elimination 消除。" },
  { word: "emphasize", level: "SENIOR", pos: "v.", cn: "强调；着重", exampleCn: "他强调安全的重要性。", usage: "emphasis 重点；place emphasis on 重视。" },
  { word: "enable", level: "SENIOR", pos: "v.", cn: "使能够；使可能", exampleCn: "这使我们能按时完成。", usage: "enable sb. to do 使某人能够做；反义词 disable。" },
  { word: "enhance", level: "SENIOR", pos: "v.", cn: "提高；增强；改善", exampleCn: "新功能提升了体验。", usage: "enhance one's ability 提升能力；反义词 reduce。" },
  { word: "evaluate", level: "SENIOR", pos: "v.", cn: "评估；评价", exampleCn: "先评估风险再投资。", usage: "evaluate the effect 评估效果；evaluation 评估。" },
  { word: "evident", level: "SENIOR", pos: "adj.", cn: "明显的；明白的", exampleCn: "原因显而易见。", usage: "It is evident that 显然；evidently 显然地。" },
  { word: "exceed", level: "SENIOR", pos: "v.", cn: "超过；超出", exampleCn: "花费超出了预算。", usage: "exceed the limit 超限；excess 过量（名词）。" },
  { word: "expand", level: "SENIOR", pos: "v.", cn: "扩张；扩大；扩展", exampleCn: "业务正在扩张。", usage: "反义词 shrink；expansion 扩张。" },
  { word: "expose", level: "SENIOR", pos: "v.", cn: "暴露；使接触", exampleCn: "别让孩子暴露于阳光下。", usage: "expose...to 使……暴露于；exposure 暴露。" },
  { word: "former", level: "SENIOR", pos: "adj.", cn: "以前的；前者的", exampleCn: "两者相比，前者更好。", usage: "the former...the latter 前者……后者；反义词 latter。" },
  { word: "fundamental", level: "SENIOR", pos: "adj.", cn: "基本的；根本的", exampleCn: "这是基本原则。", usage: "fundamentally 根本上；近义词 basic/essential。" },
  { word: "grasp", level: "SENIOR", pos: "v.", cn: "抓住；理解；掌握", exampleCn: "我领会了要点。", usage: "grasp the meaning 领会含义；grasp at 试图抓住。" },
  { word: "guarantee", level: "SENIOR", pos: "v.", cn: "保证；担保", exampleCn: "质量保证两年。", usage: "guarantee to do 保证做；名词 guarantee 保修。" },
  { word: "identify", level: "SENIOR", pos: "v.", cn: "识别；确认；认出", exampleCn: "请确认你的身份。", usage: "identify with 认同；identification 识别/身份证。" },
  { word: "immediate", level: "SENIOR", pos: "adj.", cn: "立即的；直接的", exampleCn: "这需要立刻处理。", usage: "immediately 立刻；an immediate response 即时回应。" },
  { word: "indicate", level: "SENIOR", pos: "v.", cn: "表明；指示；象征", exampleCn: "数据表明趋势向好。", usage: "indication 迹象；indicator 指标。" },
  { word: "insist", level: "SENIOR", pos: "v.", cn: "坚持；坚决要求", exampleCn: "他坚持要去。", usage: "insist on doing 坚持做；insist that + 虚拟语气。" },
  { word: "intend", level: "SENIOR", pos: "v.", cn: "打算；想要", exampleCn: "我本打算去，但没去成。", usage: "intend to do 打算做；intention 意图。" },
  { word: "interpret", level: "SENIOR", pos: "v.", cn: "解释；口译；理解", exampleCn: "他口译了领导的讲话。", usage: "interpreter 口译员；interpretation 解释/阐释。" },
  { word: "involve", level: "SENIOR", pos: "v.", cn: "涉及；使参与；包含", exampleCn: "这事关每个人。", usage: "involve doing 需要（做）；be involved in 参与。" },
  { word: "justify", level: "SENIOR", pos: "v.", cn: "证明……正当；辩护", exampleCn: "他为自己决定辩护。", usage: "justify doing 证明做……合理；justification 理由。" },
  { word: "maintain", level: "SENIOR", pos: "v.", cn: "维持；保养；坚称", exampleCn: "请维持现场秩序。", usage: "maintain a habit 保持习惯；maintenance 维护。" },
  { word: "negotiate", level: "SENIOR", pos: "v.", cn: "谈判；协商", exampleCn: "双方正在谈判。", usage: "negotiate with 与……谈判；negotiation 谈判。" },
  { word: "obtain", level: "SENIOR", pos: "v.", cn: "获得；得到", exampleCn: "他取得了许可。", usage: "较正式「得到」；近义词 get/acquire；反义词 lose。" },
  { word: "occupy", level: "SENIOR", pos: "v.", cn: "占据；占领；使忙碌", exampleCn: "军队占领了城市。", usage: "be occupied with 忙于；occupied 被占用的。" },
  { word: "oppose", level: "SENIOR", pos: "v.", cn: "反对；反抗", exampleCn: "他反对这项计划。", usage: "oppose doing 反对做；opposite 相反的；反义词 support。" },
  { word: "participate", level: "SENIOR", pos: "v.", cn: "参与；参加", exampleCn: "大家积极参与讨论。", usage: "participate in 参加；participation 参与。" },
  { word: "perceive", level: "SENIOR", pos: "v.", cn: "察觉；理解；认知", exampleCn: "我看出他的意图。", usage: "perceive...as 把……视为；perception 感知。" },
  { word: "precise", level: "SENIOR", pos: "adj.", cn: "精确的；准确的", exampleCn: "请给出精确的数字。", usage: "precisely 精确地；precision 精确度。" },
  { word: "preserve", level: "SENIOR", pos: "v.", cn: "保护；保存；腌制", exampleCn: "我们要保护文物。", usage: "preserve the environment 保护环境；preservation 保护。" },
  { word: "promote", level: "SENIOR", pos: "v.", cn: "促进；提升；促销", exampleCn: "这能促进合作。", usage: "promote peace 促进和平；promotion 晋升/促销。" },
  { word: "propose", level: "SENIOR", pos: "v.", cn: "提议；建议；求婚", exampleCn: "他提出一个新方案。", usage: "propose doing/to do 提议做；proposal 提议。" },
  { word: "reluctant", level: "SENIOR", pos: "adj.", cn: "不情愿的；勉强的", exampleCn: "他勉强同意了。", usage: "be reluctant to do 不愿做；reluctantly 不情愿地。" },
  { word: "reveal", level: "SENIOR", pos: "v.", cn: "揭示；透露；展现", exampleCn: "真相终于大白。", usage: "反义词 conceal/hide；reveal a secret 泄露秘密。" },
  { word: "secure", level: "SENIOR", pos: "adj./v.", cn: "安全的；获得；固定", exampleCn: "请确保安全。", usage: "作形容词「安全的」；作动词「获得/保护」；security 安全。" },
  { word: "significant", level: "SENIOR", pos: "adj.", cn: "重要的；显著的", exampleCn: "这一发现意义重大。", usage: "significantly 显著地；近义词 important/crucial。" },
  { word: "sophisticated", level: "SENIOR", pos: "adj.", cn: "复杂精密的；老练的", exampleCn: "这台设备很先进。", usage: "形容技术/机械先进复杂；反义词 simple。" },
  { word: "specific", level: "SENIOR", pos: "adj.", cn: "具体的；特定的", exampleCn: "请给具体信息。", usage: "反义词 general；specifically 具体地。" },
  { word: "sufficient", level: "SENIOR", pos: "adj.", cn: "足够的；充足的", exampleCn: "资金很充足。", usage: "反义词 insufficient；sufficiently 足够地。" },
  { word: "survive", level: "SENIOR", pos: "v.", cn: "幸存；活下来；比……活得长", exampleCn: "他幸存于那场地震。", usage: "survive on 靠……生存；survival 生存。" },
  { word: "tolerate", level: "SENIOR", pos: "v.", cn: "容忍；忍受", exampleCn: "我难以忍受噪音。", usage: "tolerate doing 忍受做；tolerance 容忍度。" },
  { word: "transform", level: "SENIOR", pos: "v.", cn: "使转变；改革", exampleCn: "改革改变了这座城市。", usage: "transform...into 把……变成；transformation 转变。" },
  { word: "transparent", level: "SENIOR", pos: "adj.", cn: "透明的；清澈的", exampleCn: "玻璃是透明的。", usage: "反义词 opaque；transparency 透明度。" },
  { word: "undertake", level: "SENIOR", pos: "v.", cn: "承担；着手做；答应", exampleCn: "他承担了这项任务。", usage: "undertake to do 答应做；undertaking 事业/任务。" },
  { word: "unique", level: "SENIOR", pos: "adj.", cn: "独特的；独一无二的", exampleCn: "每个指纹都独一无二。", usage: "反义词 common；be unique to 为……所独有。" },
  { word: "violate", level: "SENIOR", pos: "v.", cn: "违反；侵犯", exampleCn: "此举违反了合同。", usage: "violate the law 违法；violation 违反。" },
  { word: "vital", level: "SENIOR", pos: "adj.", cn: "至关重要的；生命的", exampleCn: "水对生命至关重要。", usage: "be vital to 对……极重要；近义词 crucial。" }
];
